### PR TITLE
Adding infographics to tokens section

### PR DESCRIPTION
**Pull request by Buddhika-Pathirathna**
### Related links
Card - [595](https://github.com/casper-network/docs/issues/595)

### Changes

Added the provided images to the Design --> Token page.

### CODE REVIEW

**Comment by ipopescu** [comment]
@Buddhika-Pathirathna are the PNGs missing?

**Review by ipopescu — CHANGES_REQUESTED** [review]
I want to request several updates for the image content. Who do I speak with about that? Maybe we need to hold a 15 min call with the reviewers of this PR.

**Comment by Buddhika-Pathirathna** [comment]
> I want to request several updates for the image content. Who do I speak with about that? Maybe we need to hold a 15 min call with the reviewers of this PR.

Hi @ipopescu - Please contact Ricky Liu (GitHub - lhg9865 ) for more information.

**Comment by ipopescu** [comment]
Hi @Buddhika-Pathirathna I belive we discussed closing this PR for now, until the images are reviewed internally.

**Pull request closed without merging**
