### PR TITLE
New tutorial for Counter on the Casper Chain

### PR DESCRIPTION
**Pull request by GloreenS**

### CODE REVIEW

**Comment by ipopescu** [comment]
@GloreenS please review the updates and run them locally, to make sure I didn't make any mistakes. Please also review the writing style and simplify it where possible. Otherwise, this looks good. I will approve and merge, once you get a chance to the final pass. Thanks!

**Review by ipopescu — APPROVED** [review]
Very nice work, @GloreenS!

**Comment by ipopescu** [comment]
@GloreenS I need to merge this to send to a client.

**Comment by GloreenS** [comment]
Thanks @ipopescu

**Pull request merged**
