### PR TITLE
Use tiles for tutorial list

### PR DESCRIPTION
**Pull request by andrzej-casper**
### What does this PR fix/introduce?

This PR introduces the first draft of the tiles in the Tutorials.
The lists with the tutorials have been switched out with the tiles.

Closes [#1211](https://github.com/casper-network/docs/issues/1211).

### Additional context

This is backport of [experimental PR](https://github.com/casper-network/docs-new/pull/206) authored by @KMCreatesWorlds.

### Checklist

- [x] Docs are successfully building - `yarn install && yarn run build`.
- [x] All technical procedures have been tested.

### CODE REVIEW

**Comment by andrzej-casper** [comment]
This PR stays draft, as we discussed that tiles UI is a bit confusing and should be improved:

image

**Comment by ipopescu** [comment]
@andrzej-casper @KMCreatesWorlds I recommend opening an issue to refine this, and point to the [working branch](https://github.com/casper-network/docs/tree/1211-experiment-with-tiles-and-cards-in-tutorials-section) in the issue. Otherwise, this draft PR might stay open for a long time.

**Comment by andrzej-casper** [comment]
@ipopescu This PR is already linked with issue #1211:

image

The issue is pointing to this PR:

image

**Comment by andrzej-casper** [comment]
@ipopescu It is not possible to link just a branch name, as there is already PR for it:

image

**Comment by andrzej-casper** [comment]
Closing, as tiles are currently outside the focus of the documentation team.

**Pull request closed without merging**
