### PR TITLE
Add ruby-sdk

### PR DESCRIPTION
**Pull request by saitgulmez**
### Related links

https://github.com/saitgulmez/casper-ruby-sdk

### Changes

Add ruby-sdk to the list of Casper SDK s : https://docs.casperlabs.io/sdk/

### CODE REVIEW

**Comment by ipopescu** [comment]
@saitgulmez, thanks for submitting this update and for creating the Ruby SDK. Before we list it in our documentation, could you please provide more information: has anyone peer-reviewed this code?

**Comment by saitgulmez** [comment]
@ipopescu, Ruby SDK is an open source project funded by DEVxDAO. It was reviewed by CRDAO. You can see code review details [here](https://github.com/CodeReviewDAO/dxd_codereview/tree/main/Reviews/341%20-%20Casper%20Ruby%20SDK/3%20-%20Final).

**Comment by ipopescu** [comment]
@saitgulmez, thank you very much for these additional details. Please stay tuned while our development team reviews this PR.

**Comment by ipopescu** [comment]
@saitgulmez, does the SDK follow the specification listed here: https://docs.casperlabs.io/dapp-dev-guide/sdkspec/introduction/?

**Comment by ipopescu** [comment]
@saitgulmez , please provide the additional information requested -- does the SDK follow the specification listed here: https://docs.casperlabs.io/dapp-dev-guide/sdkspec/introduction/?

**Comment by ipopescu** [comment]
Closing until we get more info. Please re-open with the additional info requested.

**Pull request closed without merging**
