### PR TITLE
1202 index file cleanup

### LINKED ISSUE #1202: Cleanup index files from collapsible categories
Thanks @andrzej-casper for finding a solution to duplicated headings in collapsible categories and fixing the breadcrumbs.

The fix:
- There is no need for additional Introduction/Overview/Index pages in sidebar
- The category itself can be clicked
- This also fixes breadcrumbs

To do: remove all index.md files from every collapsible category. 

Current behavior:

New desired behavior:

Current behavior:

New desired behavior:

CC @ACStoneCL

### PR DESCRIPTION
**Pull request by ipopescu**
### What does this PR fix/introduce?

- Removes unnecessary Introduction/Overview/Index pages in sidebar
- Adds missing index files in the operators section, where they seemed necessary
- Clean up of the operators section since the index files were introduced. As a result of this PR, the operators section doesn't need to be updated in cards #1200 and #1199.

Open question for @ACStoneCL: sometimes articles are missing in a sidebar, to keep titles shorter, but I kept them in this PR. Examples: `Archive and Restore a DB` vs. `Archive and Restore DB`, `Move a Node` vs. `Move Node`, `Join a Network` vs. `Join Network`. What do you think? 

Screenshot 2023-07-17 at 19 48 28

I've discovered issue #1216  while working on this PR.

Closes #1202 

### Checklist

- [x] Docs are successfully building - `yarn install && yarn run build`.
- [x] For new **internal** links I used *relative file paths* (with .md extension) - e.g. `../../faq/faq-general.md` - instead of introducing *absolute file path*, or *relative/absolute URL*.
- [x] All external links have been verified with `yarn run check:externals`.
- [x] My changes follow the [Casper docs style guidelines](https://docs.casper.network/resources/contribute-to-docs/).

### Reviewers
@ACStoneCL @andrzej-casper 

FYI @Adrian-Wrona

### CODE REVIEW

**Review by ACStoneCL — APPROVED** [review]
Content LGTM - as far as the titles in the sidebar, I don't have a strong opinion beyond making sure that they are easily readable.

**Comment by ipopescu** [comment]
Thanks @ACStoneCL!

**Review by andrzej-casper — CHANGES_REQUESTED** [review]
Now it's much easier to navigate sidebar and breadcrumbs are working :grin: 

---

I found one place where collapsible category is not merged with index (thus breadcrumb is broken):

image

I suggest moving subpage _Introduction_ directly to _Why Build on Casper_, and moving out _Ecosystem Open-Source Software_.

**Comment by andrzej-casper** [comment]
Top level sections can be shown with #1219.

**Comment by ipopescu** [comment]
@andrzej-casper I am addressing your request in this branch: [1200_navigation_resources](https://github.com/casper-network/docs/tree/1200_navigation_resources) I started doing the change you requested right after our call, but the PR got too big. Please approve this one, and then I will raise another PR for the  [1200_navigation_resources](https://github.com/casper-network/docs/tree/1200_navigation_resources) branch. I am trying to break down the work in manageable PRs, but there is still some inter-connectedness.

**Review by andrzej-casper — APPROVED** [review]
@ipopescu Let's merge it then!

**Pull request merged**
