### PR TITLE
Restructured content for creating keys

### PR DESCRIPTION
**Pull request by ipopescu**
### Related links

Parent card with requirements: https://github.com/casper-network/docs/issues/170

### Changes

Merged content referencing keys and account creation in the how-to guides and in the dapp developers' section:
- Renamed “Working with Cryptographic Keys”  to “Accounts and Cryptographic Keys”
- Moved the content related to accounts and key generation from "source/docs/casper/workflow/setup.md" to the “Accounts and Cryptographic Keys” section in "source/docs/casper/dapp-dev-guide/keys.md"
- Tried to merge the content in a way that flows what was existing
- Removed any mention of keys from "source/docs/casper/workflow/setup.md"
- Removed the 3 files from the intro and kept them only for option 1, because option 2 only downloads the secret key
- In option 2, I reworked the text, because the download of the secret key changed (it is now automatic after creating the account).

### Notes
- I have checked all links and cross-references to the updated headers (while running the app locally)
- A similar restructuring needs to happen for the Command line client, and I’ve opened card #195.

### CODE REVIEW

**Comment by ipopescu** [comment]
@GloreenS, since you are most familiar with this content, could you please review? @Fraser999 fyi.

**Review by GloreenS — APPROVED** [review]
@ipopescu Here are a couple suggestions, rest of the changes look good. Thanks!
- Now that the two topics are merged, I think we need to mention that the `casper-client keygen .` command creates EdDSA keys by default.
- Also, maybe we should mention that we can create both types of keys using the block explorer too. Because as of now both types of keys only appear under the command-line client instructions.

**Comment by ipopescu** [comment]
@GloreenS, I did quite a lot of restructuring to address your suggestions, so I am re-requesting your review. Thanks so much!

**Review by GloreenS — APPROVED** [review]
Changes look good!

**Comment by ipopescu** [comment]
> Changes look good!

Thanks @GloreenS!

**Pull request merged**
