### PR TITLE
add scala-sdk

### PR DESCRIPTION
**Pull request by abahmanem**
### Related links

https://github.com/abahmanem/casper-scala-sdk

https://github.com/abahmanem/camel-casper

### Changes

1- Add scala-sdk to the list of Casper SDK s  :   https://docs.casperlabs.io/sdk/

2- Change git repositories for Camel Casper connector and Casper Scala SDK projects in Casper Ecosystem page : 

https://docs.casperlabs.io/dapp-dev-guide/build-on-casper/casper-open-source-software/

Repository is no longer :  https://github.com/caspercommunityio

The new repository for these two projects is :  https://github.com/abahmanem

### CODE REVIEW

**Review by ipopescu — CHANGES_REQUESTED** [review]
More information is required, the current description is empty. Why is this change requested? I still see the previous repository. Has this new repository been vetted by anyone in the Casper Association or ecosystem? Who is using the repository? Only once we have these answers we can update the documenation.

**Comment by abahmanem** [comment]
Hello,

These two projects were funded by devxdao:

https://portal.devxdao.com/app/proposal/329

and

https://portal.devxdao.com/app/proposal/295

I am the OP of these two projects

These two projects have been validated by the CRDAO (https://crdao.ossa.dev/).

Following a break up with the owner of the repository (https://github.com/caspercommunityio), I no longer have access to the source codes of these two projects. As i was unable to develop them I forked on this new repository:

https://github.com/abahmanem and continued to work on them there.

You can see that there are no more commits on these two projects in the old repository for months.

These two projects will continue to live and evolve with Casper under the repository:

https://github.com/abahmanem

These changes have been validated by CRDAO and by Muhammet Kara. you can reach Muhammet for more informations.

Many thanks

**Comment by ipopescu** [comment]
Thanks for the additional information @abahmanem. I have added @mrkara as a reviewer on this PR. I still request you fill out the PR description above.

**Comment by mrkara** [comment]
@ipopescu: I confirm that the pull requester is the OP of the DxD grants for Casper Scala SDK and Apache Camel Casper connector.

The latest milestone of Scala SDK has been reviewed by the CRDAO on the repo at https://github.com/abahmanem/casper-scala-sdk with job #186, and resulted in a recommendation of PASS. It's currently in formal vote with ~48 hours left. If it passes formal vote, the review will be merged into the CRDAO repo: https://github.com/CodeReviewDAO/dxd_codereview/pull/154

**Comment by ipopescu** [comment]
Thanks, @abahmanem, I have approved it and resolved newer conflicts, and we can merge it as soon as the tests pass.

**Review by ipopescu — APPROVED** [review]

**Pull request merged**
