### PR TITLE
Update getStateRootHash params in doc

### PR DESCRIPTION
**Pull request by gRoussac**
Hi,

Not sure if this PR is relevant considering answer of https://github.com/casper-network/docs/issues/534, if not please close PR.

Signature of method getStateRootHash seems to have been updated otherwise getting following error

```
"error":{"code":-32602,"message":"Invalid params","data":"Failed to parse 'params' field: unknown variant
```

### CODE REVIEW

**Comment by ipopescu** [comment]
Maybe @hoffmannjan can help with a quick review here.

**Comment by ipopescu** [comment]
@dylanireland do you have time to help us review this PR?

**Review by ipopescu — APPROVED** [review]
I have tested @gRoussac's code found [here](https://github.com/gRoussac/casper-vite-signer), used in these samples, and it works for me. From a tech perspective, I think this is good to go.
I also cleaned up the page and removed the heavy Signer focus which is not really needed. 
As discussed, we can keep this page focused on the JS SDK and leave some of the code samples involving the Signer.
@ada Please take a quick look before merging.

**Review by ACStoneCL — APPROVED** [review]
LGTM!

**Pull request merged**
