### PR TITLE
Unified search

### PR DESCRIPTION
**Pull request by andrzej-casper**
_This is backport of https://github.com/casper-network/docs-new/pull/214, as [docs-new is deprecated](https://github.com/casper-network/docs-new/issues/215)._

---

### What does this PR fix/introduce?

Search bar unification for review.

### Reviewers

@andrzej-casper @Adrian-Wrona

### CODE REVIEW

**Comment by andrzej-casper** [comment]
I tested it locally and looks good:

image

Portal results are not loading, but this is due to quota limit - I am not familiar with mainsite and issues there.

I am approving this PR :heavy_check_mark:, but it needs second review. @bradjohnl PTAL

**Comment by bradjohnl** [comment]
@ipopescu @ACStoneCL I'd like you to confirm you are fine with this change before moving forward. The preview sites do not support the search yet, so we cannot test it there for the moment, however from the screenshots that @andrzej-casper provided we can see how it looks like.

The portal search has an issue at the moment regarding the monthly index usage quota being maxed before the end of the month, we working on it to find a solution, but most likely we will have to pay to increase the allowance

**Review by ACStoneCL — APPROVED** [review]
Everything looks fine to me, the unified box should solve a lot of confusion.

**Comment by ipopescu** [comment]
Nice work, @andrzej-casper! Thanks for implementing this. I've just tested it on the livesite.

**Comment by andrzej-casper** [comment]
@ipopescu This is the work of Miracledevs guys, I just migrated the PR :wink:

**Pull request merged**
