### PR TITLE
Add Casper Snap

### PR DESCRIPTION
**Pull request by KillianH**
### What does this PR fix/introduce?
Add Casper Snap for Metamask Flask as a wallet.

### Checklist

- [X] Docs are successfully building - `yarn install && yarn run build`.
- [X] All external links have been verified with `yarn run check:externals`.

### CODE REVIEW

**Comment by ipopescu** [comment]
@KillianH, could you add more information about these projects? Has someone in the Casper Association reviewed them?

**Comment by KillianH** [comment]
> @KillianH, could you add more information about these projects? Has someone in the Casper Association reviewed them?

Hello, this was presented to the Casper Team at the Paris Blockchain Week.

**Comment by ACStoneCL** [comment]
@KillianH Do you recall which members of the Casper Team you presented this to? Just so I can reach out to them.

**Comment by KillianH** [comment]
> @KillianH Do you recall which members of the Casper Team you presented this to? Just so I can reach out to them.

Alizee / Piotr and I think Andrzej etc

**Review by ACStoneCL — APPROVED** [review]

**Pull request merged**
