### PR TITLE
Make links relative

### PR DESCRIPTION
**Pull request by andrzej-casper**
### General description

This PR converts Markdown links into **relative file paths (with .md extensions)**. This provides the following benefits:

- Links will keep working on the GitHub interface and many Markdown editors.
- Moving files around the folders can be tracked by your editor, and some editors may automatically update file links.
- A [versioned doc](https://docusaurus.io/docs/versioning) will link to another doc of the exact same version.
-  Updating the `trailingSlash` config will be possible without breaking links.

### Not convinced about relative references?

Just open the latest [Querying a Casper Network](https://github.com/casper-network/docs/blob/e592761ce00b6a012934317daa87de9a186ee39d/source/docs/casper/workflow/developers/querying.md) page and click the first available link - absolute one :fire::

image

Boom:

image

### How do I review this PR?

- First commit contains a few manual fixes - easy to go through.
- All changes in second commit were made **automatically** with my custom Rust tool, and I believe there is no place for error. So there is not much to check - `yarn build` should be enough - but you can always try to prove me wrong :wink:.

### Future work

All slug references should be replaced as well, i.e.:

- /counter
- /counter-testnet
- /dapp-dev-guide
- /sdk
- /staking
- /tutorials
- /workflow
- /writing-contracts

This requires small manual effort, but since this is not related with upcoming docs restructuring, I leave that work for someone else :relaxed:.

### CODE REVIEW

**Comment by ipopescu** [comment]
@andrzej-casper please open an issue in docs for any **future work**, describing the behavior or outcome you wish to see after the issue is resolved. Please add more details or some examples, because I am not clear why "All slug references should be replaced as well".

Note that on the live site, we do not have a broken link as outlined above in the screenshots.

**Comment by andrzej-casper** [comment]
@ipopescu When this PR is merged, I will create issue for slug conversion :+1: And why they should be replaced? Because they are just like the absolute links: they work in _Docuzaurus_ **only**, but not directly on _GitHub_ (or other markdown editor).

Let me explain what is happening here. For example there is absolute link `/dapps-dev-guide/setup.md`, which can be resolved differently, depending on what is considered as **root directory** (/):
- for Docuzaurus it is `[repo]/source/docs`, so we get `[repo]/source/docs/dapps-dev-guide/setup.md` :heavy_check_mark: 
- for GitHub/Markdown editor it is `[repo]/`, so we get `[repo]/dapps-dev-guide/setup.md` :x: 
- for PC filesystem it is `[disk]/`, so we get `[disk]/dapps-dev-guide/setup.md` :x: 

Relative links (unlike absolute ones, or slugs) will work in every context.

**Comment by ipopescu** [comment]
@andrzej-casper, could you please resolve the conflicts? We had a PR merge yesterday.
Also, the original PR template had a checklist. Could you please indicate whether or not the following apply:

- [ ] I ran the docs locally using `yarn install` and `yarn run start`.
- [ ] All links (internal and external) have been verified. => this could be via script

**Review by ipopescu — APPROVED** [review]
LGTM! The build passes, and we will rely on the automated link checker here.

I ran the site locally and checked a few links manually.

I visually scrolled through the changes, and they look good. Good job, @andrzej-casper.

**Comment by andrzej-casper** [comment]
@ipopescu Conflicts resolved, plus checklist:

- [x] I ran the docs locally using `yarn install` and `yarn run start`.
- [x] All links (internal and external) have been verified. => This could be via script

**Comment by ipopescu** [comment]
@andrzej-casper @darthsiroftardis I recommend merging this PR as it looks good to me. This way, we also unblock the next restructuring PR.

**Pull request merged**
