### PR TITLE
Ledger tutorial feedback

### PR DESCRIPTION
**Pull request by ipopescu**
Addressing additional feedback for the Ledger tutorial: https://docs.casperlabs.io/en/latest/workflow/ledger-setup.html, from pull request #262.

### CODE REVIEW

**Review by goral09 — APPROVED** [review]
I preferred the version where the buttons' labels were in bold, to make it easier to see from the rest of the text, but it's my personal preference and not a blocker.

**Comment by ipopescu** [comment]
@goral09 I have reconsidered and made the button labels bold. I prefer them too. I changed them when Ramsin said that there was a rendering problem. But I tested the site locally and the bold text seems readable. Thanks for the review!

**Comment by ramujin** [comment]
I had actually suggested "**both**" bold and quoted button text because bolded text on the black theme of Github does not have much contrast. I'm attaching a screenshot so you can see what I mean. It's only a minor nitpick, so I wouldn't open another PR for it, especially since you already merged it.

Screen Shot 2021-08-03 at 12 01 32

**Comment by ipopescu** [comment]
> I had actually suggested "**both**" bold and quoted button text because bolded text on the black theme of Github does not have much contrast. I'm attaching a screenshot so you can see what I mean. It's only a minor nitpick, so I wouldn't open another PR for it, especially since you already merged it.
> 
> Screen Shot 2021-08-03 at 12 01 32

I understand now. Thanks @ramujin. If I am in this area again, I might get a chance to update it.

**Pull request merged**
